import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LeftSidebar from "@/components/LeftSidebar";
import Profile from "@/components/Sidebar/Profile";
import Navigation from "@/components/Sidebar/Navigation";
import MyPlaylists from "@/components/Sidebar/MyPlaylists";
import RightSidebar from "@/components/RightSidebar";
import Header from "@/components/Header";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Search } from "lucide-react";
import HeaderNavigation from "@/components/Header/HeaderNavigation";
import HeaderSearch from "@/components/Header/HeaderSearch";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={cn(
          "min-h-screen bg-[#313131] font-sans w-full h-full",
          fontSans.variable
        )}
      >
        <div className=" flex h-full ">
          <LeftSidebar/>
          <div className="flex-1">
            <Header/>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
